# Generated by Django 6.0.1 on 2026-01-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
