# Generated by Django 6.0.1 on 2026-01-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
            ],
            options={
                'db_table': 'aboutus',
            },
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('addr', models.TextField()),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
    ]
