# Generated by Django 6.0.1 on 2026-01-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_aboutus_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(default=0)),
                ('pwd', models.CharField(max_length=50)),
                ('phno', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
