# Generated by Django 6.0.1 on 2026-01-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
