# Generated by Django 6.0.1 on 2026-01-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='privilage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('edicon', models.CharField(max_length=5)),
                ('ediabout', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'privilage',
            },
        ),
    ]
