# Generated by Django 6.0.1 on 2026-01-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_privilage'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilage',
            name='edit_about',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='privilage',
            name='edit_contact',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='privilage',
            name='edit_students',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='privilage',
            name='manage_privileges',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='privilage',
            name='manage_users',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='privilage',
            name='view_about',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='privilage',
            name='view_contact',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='privilage',
            name='view_students',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='privilage',
            name='ediabout',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='privilage',
            name='edicon',
            field=models.CharField(default='no', max_length=5),
        ),
    ]
