# Generated by Django 6.0.1 on 2026-01-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_privilage_edit_about_privilage_edit_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilage',
            name='ediabout',
        ),
        migrations.RemoveField(
            model_name='privilage',
            name='edicon',
        ),
        migrations.RemoveField(
            model_name='privilage',
            name='edit_about',
        ),
        migrations.RemoveField(
            model_name='privilage',
            name='edit_contact',
        ),
        migrations.RemoveField(
            model_name='privilage',
            name='edit_students',
        ),
        migrations.RemoveField(
            model_name='privilage',
            name='manage_privileges',
        ),
        migrations.RemoveField(
            model_name='privilage',
            name='manage_users',
        ),
        migrations.RemoveField(
            model_name='privilage',
            name='view_about',
        ),
        migrations.RemoveField(
            model_name='privilage',
            name='view_contact',
        ),
        migrations.RemoveField(
            model_name='privilage',
            name='view_students',
        ),
        migrations.AddField(
            model_name='privilage',
            name='delete_students_details',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='privilage',
            name='edit_aboutus',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='privilage',
            name='edit_contactus',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='privilage',
            name='edit_student_details',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='privilage',
            name='manage_privileges',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='privilage',
            name='manage_users',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='privilage',
            name='search_students_information',
            field=models.CharField(default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='privilage',
            name='view_student_details',
            field=models.CharField(default='no', max_length=5),
        ),
    ]
